### ISSUE TITLE
一直被take的Tag平仓是什么原因?

### ISSUE THREAD

**Issue by stdeson** [banbox/banbot#53]
# 1 问题: 
我这边用我这个策略回测时, 开了很多单, 每一个单的平仓tag都是take, 都是上一根k线开的仓, 下一根k线就平掉了, 
而且这个take不是我写的CloseOder的Tag, 想知道它是怎么被触发的?

![Image](https://github.com/user-attachments/assets/b96953dc-ba98-4ab1-9d0e-a805041c4c5e)

![Image](https://github.com/user-attachments/assets/81294161-2f60-4d43-8ae7-40a7941cf17d)

# 2 如何复现:
配置:
config.yml
```yaml
name: ban
env: dry_run  # prod表示生产网络，test表示测试网络
leverage: 1  # 杠杆倍数，仅合约市场有效
limit_vol_secs: 5  # 智能计算限价, 按成交量取订单簿价格的过期时间，单位：秒，默认10
put_limit_secs: 120  # 在此预期时间内能成交的限价单，才提交到交易所，单位：秒，默认120
account_pull_secs: 60  # 定期更新账户余额和持仓的间隔秒数，默认60秒
market_type: linear  # 现货(spot)还是U合约(linear)
contract_type: swap  # swap(永续) future到期合约
odbook_ttl: 1000  # 每多少ms重新取订单簿，默认500
concur_num: 2  # 标的K线并发下载数，默认2个标的
order_type: market  # 下单类型：market市价单  limit限价单
stop_enter_bars: 20  # 限价入场单超过多少个蜡烛未成交则取消入场，默认0不启用
prefire: 0  # 是否在bar即将完成时，提前10%时间触发OnBar
margin_add_rate: 0.66  # 交易合约时，如出现亏损，亏损达到初始保证金比率的此值时，进行追加保证金，避免强平，默认0.66
stake_amount: 500  # 单笔订单默认本金，优先级低于stake_pct, 单位是USDT, 如果是币合约, 就会买相同价值的币
# stake_pct: 10  # 单笔开单金额百分比，名义价值
max_stake_amt: 500  # 单笔上限500，仅stake_pct有值时有效
draw_balance_over: 0  # 余额超过此值时，超出部分自动提现，不用于后续交易，仅用于回测, 0表示禁用, -1表示每次盈利后保留初始本金，其余提现
close_on_stuck: 20  # 超时20分钟未收到K线时自动全部平仓，默认20。（仅实盘生效）
min_open_rate: 0.5  # 最小开单比率，余额不足单笔金额时，余额/单笔金额高于此比率允许开单，默认0.5即50%
low_cost_action: ignore  # 开单金额不足最小金额时的动作：ignore/keepBig/keepAll
bt_net_cost: 3  # 回测时下单延迟，可用于模拟滑点，单位：秒，默认15
relay_sim_unfinish: false  # 交易新品种时(回测/实盘)，是否从开始时间未平仓订单接力开始交易
order_bar_max: 500   # 查找开始时间未平仓订单向前模拟最大bar数量
ntp_lang_code: none  # ntp真实时间同步，默认none不启用，支持的代码：zh-CN, zh-HK, zh-TW, ja-JP, ko-KR, zh-SG, global(表示全球ntp服务器：google、apple、facebook...)
time_start: '20250101'  # K线起始时间，支持时间戳、日期、日期时间等，用于回测、数据导出等
time_end: '20250501'  
wallet_amounts:  # 钱包余额，用于回测
  USDT: 30000
stake_currency: ['USDT']  # 限定只交易定价币为这些的交易对
fatal_stop:   # 全局止损，当全局损失达到限制时，禁止下单
  '1440': 0.1  # 一天损失10%
  '180': 0.2  # 3小时损失20%
  '30': 0.3  # 半小时损失30%
fatal_stop_hours: 8  # 触发全局止损时，禁止开单的小时；默认8
run_timeframes: ['1m']  # 机器人允许运行的所有时间周期。策略会从中选择适合的最小周期，此处优先级低于run_policy
pairs: ['DOGE/USDT:USDT']  # 给定交易币种列表(静态)，如不为空，pairlists会被忽略
strat_perf:
  enable: false # 是否启用策略币对效果追踪，自动降低亏损较多的币种开单金额
  log_freq: '4h'  # 每4小时输出一次绩效
  trade_metrics: true  # 详细统计每笔交易的持仓时间、盈亏比等
  calc_sharpe: true  # 计算夏普比率（年化）
  calc_max_dd: true  # 计算最大回撤
  benchmark: "BTC/USDC:USDC"  # 对比基准
  risk_free_rate: 0.02  # 无风险利率（影响夏普比率计算）
  min_od_num: 5 # 最小5，默认5，单币种至少5笔订单后才参与评估（避免偶然性）
  max_od_num: 30 # 单币种最多统计30笔订单（防止过时数据影响）
  min_job_num: 10 # 最小标的数量，默认10，至少10个交易对达标才会触发动态调整
  mid_weight: 0.2 # 中等表现币种的开单金额权重（基准为1.0）
  bad_weight: 0.1 # 差表现币种的开单金额权重
run_policy:
  - name: custom:fantan  # 策略名称
    run_timeframes: ['1m']  # 此策略支持的时间周期，提供时覆盖根层级的run_timeframes
    max_pair: 30  # 此策略允许的最大标的数量
    max_open: 5  # 此策略最多几个未平仓订单
    max_simul_open: 1  # 在一个bar上，最大同时打开订单数量
    order_bar_max: 0  # 非0时覆盖全局默认order_bar_max
    stake_rate: 1 # 此策略的开单倍率
    stop_loss: 0.05  # 此策略的止损比率，如 5% 或 0.05
    dirt: any # any/long/short
pairlists:
  - name: VolumePairList
    limit: 100
    limit_rate: 1
    min_value: 100000
    cache_secs: 7200
    back_period: 7d
  - name: PriceFilter
    max_unit_value: 100
    precision: 0.0015
    min: 0.1
    max: 3000
  - name: RateOfChangeFilter
    back_days: 5
    min: 0.03
    max: 10
    cache_secs: 1440
  - name: SpreadFilter
    max_ratio: 0.005
  - name: CorrelationFilter
    min: -1
    max: 1
    timeframe: 1m
    back_num: 60
    sort: asc
    top_n: 50
  - name: VolatilityFilter
    back_days: 10
    max: 1
    min: 0.05
  - name: AgeFilter
    min: 180
  - name: OffsetFilter
    reverse: false
    offset: 0
    rate: 0.5
    limit: 20
  - name: ShuffleFilter
    seed: 42
exchange:
  name: binance
  binance:
    proxy: http://127.0.0.1:7890
    fees:
      linear:
        taker: 0.00045
        maker: 0.00018
database:
  retention: all
  max_pool_size: 50
  auto_create: true
  url: postgresql://postgres:123@[127.0.0.1]:5432/ban
spider_addr: 127.0.0.1:23895  # 要先启动内置爬虫服务banbot spider
rpc_channels:
  wx_notify:  # 企业微信机器人报警
    corp_id: ww0f12345678b7e
    agent_id: '1000002'
    corp_secret: b123456789_1Cx1234YB9K-MuVW1234
    touser: '@all'
    type: wework
    msg_types: [exception]
    accounts: []
    keywords: []
    retry_num: 0
    retry_delay: 1000
    disable: true
webhook:
  entry:
    content: "{name} {action}\nSymbol: {pair} {timeframe}\nTag: {strategy}  {enter_tag}\nPrice: {price:.5f}\nCost: {value:.2f}"
  exit:
    content: "{name} {action}\nSymbol: {pair} {timeframe}\nTag: {strategy}  {exit_tag}\nPrice: {price:.5f}\nCost: {value:.2f}\nProfit: {profit:.2f}"
  status:
    content: '{name}: {status}'
  exception:
    content: '{name}: {status}'
api_server:
  enable: true
  bind_ip: 0.0.0.0
  port: 8001
  jwt_secret_key: '123456789'
  users:
    - user: ban
      pwd: '123'
      acc_roles: {user1: admin}

```

config.local.yml
```yaml
# 保存需要经常修改的配置，会覆盖config.yml中的同名项
market_type: linear
env: test  # prod表示生产网络，test表示测试网络
time_start: "20250101"
time_end: "20250501"
pairs: ['ETH/USDT:USDT']
run_policy: 
  - name: custom:fantan
    run_timeframes: ['1m']
accounts: 
  user1:
    binance:
      prod:
        api_key: xxx
        api_secret: xxx
      test:
        api_key: xxx
        api_secret: xxx
database: 
  url: postgresql://postgres:123@127.0.0.1:5432/ban
exchange: 
  binance:
    proxy: http://127.0.0.1:7890
```

策略代码:
```go
package custom

import (
	"github.com/banbox/banbot/config"
	"github.com/banbox/banbot/core"
	"github.com/banbox/banbot/strat"
	"github.com/banbox/banbot/orm/ormo"
)

type FanTanState struct {
	LowestPrice float64 // 跟踪最低价
	HighestPrice float64 // 跟踪最高价
	InPosition bool // 是否持仓中
}

// 反弹抄底买入策略: 当反弹时买入
func FanTan(pol *config.RunPolicyConfig) *strat.TradeStrat {
	fanTanPct := pol.Def("fanTanPct", 0.0045, core.PNorm(0.0001, 0.1))
	takeProfitPct := pol.Def("takeProfitPct", 0.03, core.PNorm(0.01, 0.1))
	stopLossPct := pol.Def("stopLossPct", 0.02, core.PNorm(0.005, 0.05))
	drawDownPct := pol.Def("drawDownPct", 0.01, core.PNorm(0.001, 0.05))
	return &strat.TradeStrat{
		WarmupNum: 100,
		DrawDownExit: true,  // 启用跟踪止损
		OnStartUp: func(s *strat.StratJob) {
			s.More = &FanTanState{}
		},
		OnBar: func(s *strat.StratJob) {
			e := s.Env
			m, _ := s.More.(*FanTanState)
			curPrice := e.Close.Get(0)
			
			if !m.InPosition {
				// 当没有持仓时, 更新最低价
				if m.LowestPrice == 0 || curPrice < m.LowestPrice {
					m.LowestPrice = curPrice
				}
				reboundPct := (curPrice - m.LowestPrice) / m.LowestPrice
				if reboundPct >= fanTanPct && s.OrderNum == 0 {
					// 当下跌反弹fanTanPct时 且 当前没有未完成委托单, 开仓
					s.OpenOrder(&strat.EnterReq{
						Tag: "fan_tan",
						OrderType: core.OrderTypeLimit,
						Limit: curPrice,
						Amount: s.Strat.GetStakeAmount(s) / curPrice,
						StopLossVal: curPrice * stopLossPct,
						TakeProfitVal: curPrice * takeProfitPct,
						StopBars: 3,
					})
					m.InPosition = true
					// 最高价设为开仓价, 方便后面计算跟踪止盈
					m.HighestPrice = curPrice
				}
			} else {
				// 持仓时更新最高价
				if curPrice > m.HighestPrice {
					m.HighestPrice = curPrice
				}
			}
		},
		GetDrawDownExitRate: func(s *strat.StratJob, od *ormo.InOutOrder, maxChg float64) float64 {
			// 跟踪止盈：从最高点回撤多少时止盈
			return drawDownPct
		},
		OnCheckExit: func(s *strat.StratJob, od *ormo.InOutOrder) *strat.ExitReq {
			// 固定止盈, 指标条件止损
			e := s.Env
			curPrice := e.Close.Get(0)
			// 还没有完全成交(持仓)的订单不处理
			if od.Status < ormo.InOutStatusFullEnter {
				return nil
			}
			if !od.Short {
				if curPrice >= od.InitPrice*(1+takeProfitPct) {
					return &strat.ExitReq{
						Tag: "fixed_take_profit_long",
						OrderType: core.OrderTypeLimit,
						Limit: curPrice,
						ExitRate: 1.0,  // 平掉所有仓位
					}
				}
			}
			if od.Short {
				if curPrice <= od.InitPrice*(1-takeProfitPct)  {
					return &strat.ExitReq{
						Tag: "fixed_take_profit_short",
						OrderType: core.OrderTypeLimit,
						Limit: curPrice,
						ExitRate: 1.0,  // 平掉所有仓位
					}
				}
			}
			return nil
		},
		OnOrderChange: func(s *strat.StratJob, od *ormo.InOutOrder, chgType int) {
			m, _ := s.More.(*FanTanState)
			// 订单平仓后重置状态
			if chgType == strat.OdChgExitFill {
				m.InPosition = false
				m.LowestPrice = 0
				m.HighestPrice = 0
			}
		},
	}
}
```
可以看到我平仓的时候没有写过take这个tag, 那take应该是框架自带的, 不知道banbot框架何时会以take Tag的形式平仓呢?
